version: '3.8'
services:
  farmacia:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - /home/vscode/docker/data:/logs
